### ISSUE TITLE
评估两个模型的acc？以哪个为准啊？

### ISSUE THREAD

**Issue by Play2Boy** [xingjianleng/autoeval_baselines#3]
rt

**Comment by xingjianleng** [comment]
两个模型的acc都会考虑。例如验证集内有40个数据集，每个模型在每个数据集上会有一个acc，那么在提交的answer.txt文件中就会有80个预测的数据集acc。在评估阶段这80个值都会与ground truth计算RMSE。

关于提交的answer.txt中数据集的顺序可以参考目前验证集的比赛页面https://codalab.lisn.upsaclay.fr/competitions/10506#learn_the_details-evaluation.
